name: Java CD with AWS

on:
  push:
    branches: [ "rel" ]

env:
  S3_BUCKET_NAME: github-actions-deploy-0824

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Github submodule
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PEDIS_TOKEN }}
          submodules: true

      # Gradle 유효성 검사
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      # Gradle 빌드 & 테스트
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          
      - name: Run the Gradle package task
        run: ./gradlew build

      # before_deploy 디렉토리 생성
      - name: Make Directory
        run: mkdir -p before-deploy

      # deploy.sh, appspec.yml, jar파일 복사 후, before-deploy 내부의 모든 파일을 압축
      - name: Copy files to deploy directory
        run: |
          cp scripts/*.sh before-deploy/
          cp appspec.yml before-deploy/
          cp build/libs/*.jar before-deploy/
          cd before-deploy && zip -r footcare
          cd ../ && mkdir -p deploy
          mv before-deploy/before-deploy.zip deploy/footcare.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./footcare.zip s3://$S3_BUCKET_NAME/

  develop:
    runs-on: ubuntu-latest
    needs: build

    steps:

      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name github-actions \
          --deployment-group-name github-actions-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=github-actions-deploy-0824,bundleType=zip,key=footcare.zip \
          --region ap-northeast-2
