name: Java CI with Gradle

on:
  push:
    branches: [ "git-hub-actions", "git-hub-actions-build" ]
  pull_request:
    branches: [ "git-hub-actions", "git-hub-actions-build" ]

env:
  S3_BUCKET_NAME: github-actions-deploy-0824

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Github submodule
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PEDIS_TOKEN }}
          submodules: true

      # Gradle 유효성 검사
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      # Gradle 빌드
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run the Gradle package task
        run: ./gradlew build

      # 디렉토리 생성
      - name: Make Directory
        run: mkdir -p deploy

      # Jar 파일 복사
      - name: Copy Jar
        run: cp ./build/libs/*SNAPSHOT.jar ./deploy

      # appspec.yml 파일 복사
      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

      # script files 복사
      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      - name: Make zip file
        run: zip -r ./github-actions.zip ./deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./github-actions.zip s3://$S3_BUCKET_NAME/

  develop:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.push.branches == 'git-hub-actions' || github.event.push.branches == 'git-hub-actions-build'

    steps:

      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name github-actions \
          --deployment-group-name github-actions-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=github-actions-deploy-0824,bundleType=zip,key=github-actions.zip \
          --region ap-northeast-2