name: Java CI with Gradle

on:
  push:
    branches: [ "git-hub-actions-build" ]
  pull_request:

env:
  S3_BUCKET_NAME: github-actions-deploy-0824

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Github submodule
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PEDIS_TOKEN }}
          submodules: true

      # Gradle 유효성 검사
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      # Gradle 빌드 & 테스트
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Run the Gradle package task
        run: ./gradlew build

      - name: Upload Jacoco Report
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: ${{ github.workspace }}build/reports/jacoco/test/jacocoTestReport.xml

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml,
          token: ${{ secrets.PEDIS_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: Code Coverage
          update-comment: true
