name: Java CI with Gradle

on:
  push:
    branches: [ "git-hub-actions-build" ]
  pull_request:

env:
  S3_BUCKET_NAME: github-actions-deploy-0824

permissions:
  contents: read
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Github submodule
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PEDIS_TOKEN }}
          submodules: true

      # Gradle 유효성 검사
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      # Gradle 빌드 & 테스트
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Run the Gradle package task
        run: ./gradlew build

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml

      - name: Jacoco Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.PEDIS_TOKEN }}
          skip_check_run: true
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false

      - name: Get the Coverage info
        run: |
          echo '### Code Coverage' >> $GITHUB_STEP_SUMMARY
          echo "|Coverage coveragePercentageString|${{ steps.jacoco_reporter.outputs.coveragePercentageString }}|" >> $GITHUB_STEP_SUMMARY
      
      - uses: gazab/create-markdown-table@v1
        id: create_table
        with:
          file: ./table-data.json
          columns: '[ "Id", "Name" ]'
      - run: echo ${{ steps.create_table.outputs.table }}
          

      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-markdown
          path: ./coverage-results.md
          retention-days: 1
          
#      - name: Add Coverage Job Summary
#        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY

      - name: report
        run: ls -R
